### ISSUE TITLE
Rebrand Vuln

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/rfcs#2]
The goal of this RFCS is to rebrand [Vuln](https://github.com/NodeSecure/vuln). My idea is to rename the project to **Vulnera** because I think it sounds better.

The project will evolve to become a full-fledged project (separate from the scanner).

This rebrand also include the need of a logo (and we need a champion for this). Maybe @im-codebreaker or @tony-go can help with this (or anyone ready to contribute).

For the technical rebrand i'm ok to be the champion (or maybe @antoine-coulon could do it too).

**Comment by fraxken** [comment]
Some ideas:

![](https://v8.dev/_img/v8-outline.svg)
![](https://raw.githubusercontent.com/bloomberg/memray/main/docs/_static/images/logo.png)

Others logo from V8 are also cool: https://v8.dev/logo

**Comment by antoine-coulon** [comment]
Hello @fraxken, `Vulnera` sounds great 🚀

- About the technical rebrand I'd be happy to do it as I'm currently working on the project (and I will the whole month atleast).
- About the logo as we already discussed, I have in mind some sort of **V** representing a shield such as:

<img width="448" alt="Capture d’écran 2022-05-03 à 22 54 29" src="https://user-images.githubusercontent.com/43391199/166564222-ee9cfee4-bb44-4443-a18b-bd76b5d42e73.png">

What do you guys think?

**Comment by fraxken** [comment]
Done!
